# Generated by Django 5.2.17 on 2026-09-14 23:23

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "sms_sender_id",
                    models.CharField(
                        blank=True,
                        help_text='Shown as the SMS sender (e.g. "RokachFam") - letters and digits only, up to 10 characters. Leave blank to use the default ("FamilyTree").',
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z0-9]*$", "Letters and digits only, no spaces or symbols."
                            )
                        ],
                    ),
                ),
                (
                    "reply_to_email",
                    models.EmailField(
                        blank=True,
                        help_text="Optional - replies to this family's emails go here if set.",
                        max_length=254,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "families",
            },
        ),
        migrations.CreateModel(
            name="FamilyMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("editor", "Editor"), ("member", "Member")],
                        default="member",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tenants.family",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("account", "family"), name="unique_family_membership")
                ],
            },
        ),
    ]
