# Generated by Django 6.1.1 on 2026-09-18 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="family",
            options={"ordering": ["name", "pk"], "verbose_name_plural": "families"},
        ),
        migrations.AlterModelOptions(
            name="familymembership",
            options={"ordering": ["-joined_at", "pk"]},
        ),
        migrations.AlterField(
            model_name="family",
            name="reply_to_email",
            field=models.EmailField(
                blank=True,
                help_text="Optional - replies to this family's emails go here if set.",
                max_length=254,
                verbose_name="Reply-To email",
            ),
        ),
        migrations.AlterField(
            model_name="family",
            name="sms_sender_id",
            field=models.CharField(
                blank=True,
                help_text='Shown as the SMS sender (e.g. "RokachFam") - letters and digits only, up to 10 characters. Leave blank to use the default ("FamilyTree").',
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9]*$", "Letters and digits only, no spaces or symbols."
                    )
                ],
                verbose_name="SMS sender ID",
            ),
        ),
    ]
