# Generated by Django 6.1.1 on 2026-10-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_alter_family_options_alter_familymembership_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="email_sending_enabled",
            field=models.BooleanField(default=False, verbose_name="email sending enabled"),
        ),
        migrations.AddField(
            model_name="family",
            name="sms_sending_enabled",
            field=models.BooleanField(default=False, verbose_name="SMS sending enabled"),
        ),
    ]
