# Generated by Django 6.1.1 on 2026-10-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_family_email_sending_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="base_url",
            field=models.URLField(
                blank=True,
                help_text="Optional - overrides the site's default domain in links this family's own emails/texts generate. Leave blank to use the default.",
                verbose_name="base URL",
            ),
        ),
    ]
