# Generated by Django 6.1.1 on 2026-10-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_family_base_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="email_sending_domain",
            field=models.CharField(
                blank=True,
                help_text="Optional - overrides the domain this family's own emails send from (only safe once that domain is verified in SES with correct SPF/DKIM/DMARC - otherwise every email this family sends will fail or land as spam). Leave blank to use the shared default domain.",
                max_length=255,
                verbose_name="email sending domain",
            ),
        ),
    ]
