# Generated by Django 5.2.17 on 2026-09-14 23:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("first_name_en", models.CharField(max_length=100)),
                ("last_name_en", models.CharField(max_length=100)),
                ("first_name_he", models.CharField(blank=True, max_length=100)),
                ("last_name_he", models.CharField(blank=True, max_length=100)),
                ("nickname", models.CharField(blank=True, max_length=100)),
                (
                    "gender",
                    models.CharField(blank=True, choices=[("M", "Male"), ("F", "Female")], max_length=1),
                ),
                ("is_living", models.BooleanField(default=True, editable=False)),
                (
                    "dob_gregorian",
                    models.DateField(
                        blank=True, help_text="Civil calendar date. Enter directly if known.", null=True
                    ),
                ),
                (
                    "dob_hebrew_year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Hebrew year. Enter this directly if known, rather than letting it be computed from the Gregorian date - especially if the birth was after sunset, when the Hebrew date has already advanced to the next day.",
                        null=True,
                    ),
                ),
                (
                    "dob_hebrew_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Tishrei"),
                            (2, "Marcheshvan"),
                            (3, "Kislev"),
                            (4, "Tevet"),
                            (5, "Shvat"),
                            (6, "Adar"),
                            (7, "Adar I"),
                            (8, "Adar Ii"),
                            (9, "Nisan"),
                            (10, "Iyyar"),
                            (11, "Sivan"),
                            (12, "Tammuz"),
                            (13, "Av"),
                            (14, "Elul"),
                        ],
                        help_text="Hebrew month.",
                        null=True,
                    ),
                ),
                (
                    "dob_hebrew_day",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Hebrew day of the month.", null=True
                    ),
                ),
                (
                    "dob_year_only",
                    models.BooleanField(default=False, help_text="Only the year of birth is known"),
                ),
                (
                    "dod_gregorian",
                    models.DateField(
                        blank=True, help_text="Civil calendar date. Enter directly if known.", null=True
                    ),
                ),
                (
                    "dod_hebrew_year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Hebrew year. Enter this directly if known - e.g. from the yahrzeit already observed for this person - rather than letting it be computed from the Gregorian date. This matters even more here than for birth dates: if death was after sunset, the Hebrew date has already advanced to the next day, and getting it wrong shifts the yahrzeit itself.",
                        null=True,
                    ),
                ),
                (
                    "dod_hebrew_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Tishrei"),
                            (2, "Marcheshvan"),
                            (3, "Kislev"),
                            (4, "Tevet"),
                            (5, "Shvat"),
                            (6, "Adar"),
                            (7, "Adar I"),
                            (8, "Adar Ii"),
                            (9, "Nisan"),
                            (10, "Iyyar"),
                            (11, "Sivan"),
                            (12, "Tammuz"),
                            (13, "Av"),
                            (14, "Elul"),
                        ],
                        help_text="Hebrew month.",
                        null=True,
                    ),
                ),
                (
                    "dod_hebrew_day",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Hebrew day of the month.", null=True
                    ),
                ),
                (
                    "yahrzeit_adar_observance",
                    models.CharField(
                        choices=[("adar_i", "Adar I"), ("adar_ii", "Adar II (default)")],
                        default="adar_ii",
                        max_length=10,
                    ),
                ),
                (
                    "yahrzeit_day30_observance",
                    models.CharField(
                        choices=[
                            ("start_of_next_month", "1st of following month (default)"),
                            ("last_day_of_month", "Last day of the (now 29-day) month"),
                        ],
                        default="start_of_next_month",
                        max_length=20,
                    ),
                ),
                ("notifications_enabled", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="If this person has their own login, the account that is them.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="people",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        help_text="The family ledger this record belongs to. In-laws from a Union may belong to a different family.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people",
                        to="tenants.family",
                    ),
                ),
                (
                    "father",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children_as_father",
                        to="family.person",
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children_as_mother",
                        to="family.person",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name_en", "first_name_en"],
            },
        ),
        migrations.CreateModel(
            name="Union",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("married", "Married"), ("divorced", "Divorced"), ("widowed", "Widowed")],
                        default="married",
                        help_text="Use married for upcoming weddings",
                        max_length=10,
                    ),
                ),
                (
                    "marriage_date_gregorian",
                    models.DateField(
                        blank=True, help_text="Civil calendar date. Enter directly if known.", null=True
                    ),
                ),
                (
                    "marriage_hebrew_year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Hebrew year. Enter this directly if known, rather than letting it be computed from the Gregorian date - especially if the wedding was after sunset, when the Hebrew date has already advanced to the next day.",
                        null=True,
                    ),
                ),
                (
                    "marriage_hebrew_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Tishrei"),
                            (2, "Marcheshvan"),
                            (3, "Kislev"),
                            (4, "Tevet"),
                            (5, "Shvat"),
                            (6, "Adar"),
                            (7, "Adar I"),
                            (8, "Adar Ii"),
                            (9, "Nisan"),
                            (10, "Iyyar"),
                            (11, "Sivan"),
                            (12, "Tammuz"),
                            (13, "Av"),
                            (14, "Elul"),
                        ],
                        help_text="Hebrew month.",
                        null=True,
                    ),
                ),
                (
                    "marriage_hebrew_day",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Hebrew day of the month.", null=True
                    ),
                ),
                ("divorce_date_gregorian", models.DateField(blank=True, null=True)),
                (
                    "person_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unions_as_a",
                        to="family.person",
                    ),
                ),
                (
                    "person_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unions_as_b",
                        to="family.person",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                fields=("family", "account"), name="person_account_unique_per_family"
            ),
        ),
        migrations.AddConstraint(
            model_name="union",
            constraint=models.CheckConstraint(
                condition=models.Q(("person_a", models.F("person_b")), _negated=True),
                name="union_distinct_people",
            ),
        ),
    ]
