# Generated by Django 6.1.1 on 2026-09-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ["last_name_en", "first_name_en", "pk"]},
        ),
        migrations.AlterModelOptions(
            name="union",
            options={
                "ordering": [
                    "person_a__last_name_en",
                    "person_a__first_name_en",
                    "person_b__last_name_en",
                    "person_b__first_name_en",
                    "pk",
                ]
            },
        ),
        migrations.AlterField(
            model_name="person",
            name="dob_gregorian",
            field=models.DateField(
                blank=True,
                help_text="Civil calendar date. Enter directly if known.",
                null=True,
                verbose_name="date of birth (Gregorian)",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="dob_hebrew_day",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Hebrew day of the month.", null=True, verbose_name="Hebrew birth day"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="dob_hebrew_month",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Tishrei"),
                    (2, "Marcheshvan"),
                    (3, "Kislev"),
                    (4, "Tevet"),
                    (5, "Shvat"),
                    (6, "Adar"),
                    (7, "Adar I"),
                    (8, "Adar Ii"),
                    (9, "Nisan"),
                    (10, "Iyyar"),
                    (11, "Sivan"),
                    (12, "Tammuz"),
                    (13, "Av"),
                    (14, "Elul"),
                ],
                help_text="Hebrew month.",
                null=True,
                verbose_name="Hebrew birth month",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="dob_hebrew_year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Hebrew year. Enter this directly if known, rather than letting it be computed from the Gregorian date - especially if the birth was after sunset, when the Hebrew date has already advanced to the next day.",
                null=True,
                verbose_name="Hebrew birth year",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="dob_year_only",
            field=models.BooleanField(
                default=False, help_text="Only the year of birth is known", verbose_name="year of birth only"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="dod_gregorian",
            field=models.DateField(
                blank=True,
                help_text="Civil calendar date. Enter directly if known.",
                null=True,
                verbose_name="date of death (Gregorian)",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="dod_hebrew_day",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Hebrew day of the month.", null=True, verbose_name="Hebrew death day"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="dod_hebrew_month",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Tishrei"),
                    (2, "Marcheshvan"),
                    (3, "Kislev"),
                    (4, "Tevet"),
                    (5, "Shvat"),
                    (6, "Adar"),
                    (7, "Adar I"),
                    (8, "Adar Ii"),
                    (9, "Nisan"),
                    (10, "Iyyar"),
                    (11, "Sivan"),
                    (12, "Tammuz"),
                    (13, "Av"),
                    (14, "Elul"),
                ],
                help_text="Hebrew month.",
                null=True,
                verbose_name="Hebrew death month",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="dod_hebrew_year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Hebrew year. Enter this directly if known - e.g. from the yahrzeit already observed for this person - rather than letting it be computed from the Gregorian date. This matters even more here than for birth dates: if death was after sunset, the Hebrew date has already advanced to the next day, and getting it wrong shifts the yahrzeit itself.",
                null=True,
                verbose_name="Hebrew death year",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name_en",
            field=models.CharField(max_length=100, verbose_name="first name (English)"),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name_he",
            field=models.CharField(blank=True, max_length=100, verbose_name="first name (Hebrew)"),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name_en",
            field=models.CharField(max_length=100, verbose_name="last name (English)"),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name_he",
            field=models.CharField(blank=True, max_length=100, verbose_name="last name (Hebrew)"),
        ),
        migrations.AlterField(
            model_name="person",
            name="yahrzeit_adar_observance",
            field=models.CharField(
                choices=[("adar_i", "Adar I"), ("adar_ii", "Adar II (default)")],
                default="adar_ii",
                max_length=10,
                verbose_name="yahrzeit Adar observance",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="yahrzeit_day30_observance",
            field=models.CharField(
                choices=[
                    ("start_of_next_month", "1st of following month (default)"),
                    ("last_day_of_month", "Last day of the (now 29-day) month"),
                ],
                default="start_of_next_month",
                max_length=20,
                verbose_name="yahrzeit 30-day observance",
            ),
        ),
        migrations.AlterField(
            model_name="union",
            name="divorce_date_gregorian",
            field=models.DateField(blank=True, null=True, verbose_name="divorce date (Gregorian)"),
        ),
        migrations.AlterField(
            model_name="union",
            name="marriage_date_gregorian",
            field=models.DateField(
                blank=True,
                help_text="Civil calendar date. Enter directly if known.",
                null=True,
                verbose_name="marriage date (Gregorian)",
            ),
        ),
        migrations.AlterField(
            model_name="union",
            name="marriage_hebrew_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Hebrew day of the month.",
                null=True,
                verbose_name="Hebrew marriage day",
            ),
        ),
        migrations.AlterField(
            model_name="union",
            name="marriage_hebrew_month",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Tishrei"),
                    (2, "Marcheshvan"),
                    (3, "Kislev"),
                    (4, "Tevet"),
                    (5, "Shvat"),
                    (6, "Adar"),
                    (7, "Adar I"),
                    (8, "Adar Ii"),
                    (9, "Nisan"),
                    (10, "Iyyar"),
                    (11, "Sivan"),
                    (12, "Tammuz"),
                    (13, "Av"),
                    (14, "Elul"),
                ],
                help_text="Hebrew month.",
                null=True,
                verbose_name="Hebrew marriage month",
            ),
        ),
        migrations.AlterField(
            model_name="union",
            name="marriage_hebrew_year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Hebrew year. Enter this directly if known, rather than letting it be computed from the Gregorian date - especially if the wedding was after sunset, when the Hebrew date has already advanced to the next day.",
                null=True,
                verbose_name="Hebrew marriage year",
            ),
        ),
    ]
