# Generated by Django 6.1.1 on 2026-09-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0002_alter_person_options_alter_union_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="union",
            name="engagement_date_gregorian",
            field=models.DateField(
                blank=True,
                help_text="Civil calendar date. Enter directly if known.",
                null=True,
                verbose_name="engagement date (Gregorian)",
            ),
        ),
        migrations.AddField(
            model_name="union",
            name="engagement_hebrew_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Hebrew day of the month.",
                null=True,
                verbose_name="Hebrew engagement day",
            ),
        ),
        migrations.AddField(
            model_name="union",
            name="engagement_hebrew_month",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Tishrei"),
                    (2, "Marcheshvan"),
                    (3, "Kislev"),
                    (4, "Tevet"),
                    (5, "Shvat"),
                    (6, "Adar"),
                    (7, "Adar I"),
                    (8, "Adar Ii"),
                    (9, "Nisan"),
                    (10, "Iyyar"),
                    (11, "Sivan"),
                    (12, "Tammuz"),
                    (13, "Av"),
                    (14, "Elul"),
                ],
                help_text="Hebrew month.",
                null=True,
                verbose_name="Hebrew engagement month",
            ),
        ),
        migrations.AddField(
            model_name="union",
            name="engagement_hebrew_year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Hebrew year. Enter this directly if known, rather than letting it be computed from the Gregorian date - especially if the engagement was after sunset, when the Hebrew date has already advanced to the next day.",
                null=True,
                verbose_name="Hebrew engagement year",
            ),
        ),
    ]
