# Generated by Django 6.1.1 on 2026-09-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0003_union_engagement_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ["last_name_en", "last_name_he", "first_name_en", "first_name_he", "pk"]},
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name_en",
            field=models.CharField(blank=True, max_length=100, verbose_name="first name (English)"),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name_he",
            field=models.CharField(max_length=100, verbose_name="first name (Hebrew)"),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name_en",
            field=models.CharField(blank=True, max_length=100, verbose_name="last name (English)"),
        ),
    ]
