# Generated by Django 6.1.1 on 2026-09-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0004_alter_person_options_alter_person_first_name_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="visibility",
            field=models.CharField(
                blank=True,
                choices=[
                    ("everyone", "Everyone"),
                    ("direct_family", "Direct family only"),
                    ("immediate_family", "Immediate family only"),
                    ("nobody", "Owners/editors only"),
                ],
                default="everyone",
                help_text="Who can see this person and get notified about them (besides owners/editors, who always can). Restricting this also hides this person's own descendants from anyone who wouldn't otherwise be able to see this person - see the Help page for details.",
                max_length=20,
            ),
        ),
    ]
