# Generated by Django 6.1.1 on 2026-10-01 18:24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0005_person_visibility"),
        ("reversion", "0002_add_index_on_version_for_content_type_and_db"),
        ("tenants", "0002_alter_family_options_alter_familymembership_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "target_model",
                    models.CharField(choices=[("person", "Person"), ("union", "Union")], max_length=10),
                ),
                (
                    "link_kind",
                    models.CharField(
                        blank=True,
                        choices=[("spouse", "Spouse of"), ("father", "Father of"), ("mother", "Mother of")],
                        max_length=10,
                    ),
                ),
                ("link_union_changes", models.JSONField(blank=True, null=True)),
                ("proposed_changes", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewer_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applied_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="reversion.revision",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        help_text="Denormalized from the target (or, for a suggest-add, the submitter's own family) so a pending suggest-add has somewhere to be scoped from before its Person/Union exists.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="tenants.family",
                    ),
                ),
                (
                    "link_applied_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="reversion.revision",
                    ),
                ),
                (
                    "link_with",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestion_links",
                        to="family.person",
                    ),
                ),
                (
                    "proposed_person_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="union_suggestions_as_a",
                        to="family.person",
                    ),
                ),
                (
                    "proposed_person_b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="union_suggestions_as_b",
                        to="family.person",
                    ),
                ),
                (
                    "resulting_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="family.person",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggestions_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="family.person",
                    ),
                ),
                (
                    "target_union",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="family.union",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("proposed_person_a__isnull", True),
                                ("proposed_person_b__isnull", True),
                                ("target_model", "person"),
                                ("target_union__isnull", True),
                            ),
                            models.Q(
                                ("link_kind", ""),
                                ("link_union_changes__isnull", True),
                                ("link_with__isnull", True),
                                ("target_model", "union"),
                                ("target_person__isnull", True),
                                models.Q(
                                    models.Q(
                                        ("proposed_person_a__isnull", True),
                                        ("proposed_person_b__isnull", True),
                                        ("target_union__isnull", False),
                                    ),
                                    models.Q(
                                        ("proposed_person_a__isnull", False),
                                        ("proposed_person_b__isnull", False),
                                        ("target_union__isnull", True),
                                    ),
                                    _connector="OR",
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="suggestion_target_fields_match_target_model",
                    )
                ],
            },
        ),
    ]
