# Generated by Django 6.1.1 on 2026-10-02 11:32

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def backfill_notified_messages(apps, schema_editor):
    """Marks every existing Suggestion as already notified, via one inert placeholder Message per family.

    Without this, family.tasks.send_suggestion_digests' first run would
    treat every pending/resolved suggestion that existed before this
    feature shipped as brand new - batch-emailing owners/editors (and
    every past submitter) about activity nobody actually needs telling
    about again. A real Message row is required as the claim marker
    (Suggestion.pending_message/resolved_message are plain FKs, not
    booleans/timestamps - see those fields' own docstrings), but no real
    message was ever sent for these pre-existing rows, so this creates
    one harmless, clearly-labeled placeholder Message per affected
    family and points every historical row at it - cheaper and less
    surprising than a second "already handled, trust me" column living
    on Suggestion forever just for this one-time cutover.
    """
    Suggestion = apps.get_model("family", "Suggestion")
    Message = apps.get_model("notifications", "Message")
    now = timezone.now()

    def _placeholder_for(family_id):
        return Message.objects.create(
            direct_family_id=family_id,
            channel="email",
            destination="",
            subject="",
            body="Backfilled - predates suggestion-digest notifications.",
            status="sent",
            sent_at=now,
        )

    pending_family_ids = set(
        Suggestion.objects.filter(status="pending", pending_message__isnull=True).values_list(
            "family_id", flat=True
        )
    )
    for family_id in pending_family_ids:
        placeholder = _placeholder_for(family_id)
        Suggestion.objects.filter(family_id=family_id, status="pending", pending_message__isnull=True).update(
            pending_message=placeholder
        )

    resolved_family_ids = set(
        Suggestion.objects.filter(status__in=["approved", "rejected"], resolved_message__isnull=True)
        .values_list("family_id", flat=True)
        .distinct()
    )
    for family_id in resolved_family_ids:
        placeholder = _placeholder_for(family_id)
        Suggestion.objects.filter(
            family_id=family_id, status__in=["approved", "rejected"], resolved_message__isnull=True
        ).update(resolved_message=placeholder)


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0006_suggestion"),
        ("notifications", "0010_message_direct_family"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestion",
            name="pending_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="notifications.message",
            ),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="resolved_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="notifications.message",
            ),
        ),
        migrations.RunPython(backfill_notified_messages, migrations.RunPython.noop),
    ]
