# Generated by Django 6.1.1 on 2026-10-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0007_suggestion_digest_messages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="first_name_he",
            field=models.CharField(
                help_text='Not yet named? Use "ילד"/"ילדה" until the naming - the birthday notification recognizes those and announces a new baby instead.',
                max_length=100,
                verbose_name="first name (Hebrew)",
            ),
        ),
    ]
