# Generated by Django 5.2.17 on 2026-09-14 23:23

import django.utils.timezone
from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="E.164 format, e.g. +15551234567",
                        max_length=32,
                        null=True,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=255)),
                (
                    "preferred_channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS")], default="email", max_length=10
                    ),
                ),
                ("email_notifications_enabled", models.BooleanField(default=True)),
                ("sms_notifications_enabled", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("email__isnull", False), ("phone__isnull", False), _connector="OR"
                        ),
                        name="account_has_email_or_phone",
                    )
                ],
            },
            managers=[
                ("objects", accounts.models.AccountManager()),
            ],
        ),
    ]
