# Generated by Django 6.1.1 on 2026-09-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_account_display_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["email", "phone", "pk"]},
        ),
    ]
