# Generated by Django 6.1.1 on 2026-10-09 17:22

from django.db import migrations, models


def _backfill_last_seen_from_last_login(apps, schema_editor):
    Account = apps.get_model("accounts", "Account")
    Account.objects.filter(last_seen_at__isnull=True, last_login__isnull=False).update(
        last_seen_at=models.F("last_login")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_account_uuid_and_drop_preferred_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        # No real way to reverse this once last_seen_at starts getting
        # its own independent updates from TrackLastSeenMiddleware - noop.
        migrations.RunPython(_backfill_last_seen_from_last_login, migrations.RunPython.noop),
    ]
