# Generated by Django 5.2.17 on 2026-09-14 23:23

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

# Every family gets these event types for free (see EventType.BuiltinCode
# and AGENTS.md's "Life events are user-defined, but a few come for free" -
# global, family=None rows every family can subscribe to without defining
# their own). Seeded here (squashed history) rather than split across
# several migrations added over time - see AGENTS.md for why this file is
# one flat migration per app instead of the original iterative history.
GLOBAL_EVENT_TYPES = [
    {"code": "birthday", "name": "Birthday", "anchor": "birth", "applies_to_union": False},
    {"code": "yahrzeit", "name": "Yahrzeit", "anchor": "death", "applies_to_union": False},
    {
        "code": "anniversary",
        "name": "Anniversary",
        "anchor": "marriage",
        "applies_to_union": True,
        "default_opt_in": False,
    },
    {"code": "bar_mitzvah", "name": "Bar Mitzvah", "anchor": "birth", "applies_to_union": False},
    {"code": "bat_mitzvah", "name": "Bat Mitzvah", "anchor": "birth", "applies_to_union": False},
    {
        "code": "wedding",
        "name": "Wedding",
        "anchor": "marriage",
        "applies_to_union": True,
        "recurs": False,
        "notify_days_before": 3,
    },
    {
        "code": "broadcast",
        "name": "Broadcast",
        "anchor": "",
        "applies_to_union": False,
        "default_opt_in": True,
        "recurs": False,
        "notify_days_before": 0,
    },
]


def seed_global_event_types(apps, schema_editor):
    EventType = apps.get_model("notifications", "EventType")
    for data in GLOBAL_EVENT_TYPES:
        EventType.objects.get_or_create(family=None, code=data["code"], defaults=data)


def unseed_global_event_types(apps, schema_editor):
    EventType = apps.get_model("notifications", "EventType")
    EventType.objects.filter(family=None, code__in=[d["code"] for d in GLOBAL_EVENT_TYPES]).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("family", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("text", models.TextField()),
                (
                    "send_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When to send this - leave as-is to send immediately.",
                    ),
                ),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcasts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcasts",
                        to="tenants.family",
                    ),
                ),
                (
                    "people",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Optional - who this update is about. Narrows 'immediate family only' subscribers to whoever's immediate family to any of these people; leave blank for a family-wide update.",
                        related_name="broadcasts",
                        to="family.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-send_at"],
            },
        ),
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("code", models.SlugField()),
                ("name", models.CharField(max_length=100)),
                (
                    "anchor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("birth", "Date of birth"),
                            ("death", "Date of death (yahrzeit)"),
                            ("marriage", "Marriage date"),
                        ],
                        help_text="Blank for an event type with no anchor date of its own (e.g. Broadcast, which is sent immediately/on a schedule rather than computed from a Person/Union date field).",
                        max_length=10,
                    ),
                ),
                (
                    "applies_to_union",
                    models.BooleanField(
                        default=False, help_text="Subject is a Union (e.g. anniversary) rather than a Person"
                    ),
                ),
                (
                    "default_opt_in",
                    models.BooleanField(
                        default=True,
                        help_text="Whether people are subscribed to this event type unless they say otherwise. A family adding a more sensitive custom event type may want it to start opted out instead.",
                    ),
                ),
                (
                    "recurs",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this happens every year (birthday, yahrzeit, anniversary) or just once, in the anchor date's own year (e.g. Wedding - the marriage itself only happens once; the yearly celebration of it afterwards is the separate Anniversary event type).",
                    ),
                ),
                (
                    "notify_days_before",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="How many days ahead of the actual date to send the notification - 0 sends on the day itself (the default, right for a birthday or yahrzeit). A Wedding reminder, for example, is more useful sent a few days ahead.",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null means this is a global default available to every family.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_types",
                        to="tenants.family",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("channel", models.CharField(choices=[("email", "Email"), ("sms", "SMS")], max_length=10)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("muted", "Muted"),
                            ("subscribed", "Subscribed"),
                            ("immediate_family_only", "Immediate family only"),
                        ],
                        max_length=25,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to="notifications.eventtype",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to="family.person",
                    ),
                ),
                (
                    "union",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to="family.union",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Occurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("hebrew_year", models.PositiveIntegerField()),
                ("occurrence_date", models.DateField(help_text="The halachic date of the event this year")),
                (
                    "send_date",
                    models.DateField(
                        help_text="The date the notification actually goes out (shifted for Shabbat/Yom Tov)"
                    ),
                ),
                ("shifted_for_shabbat_or_yomtov", models.BooleanField(default=False)),
                ("is_sent", models.BooleanField(default=False)),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occurrences",
                        to="notifications.eventtype",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occurrences",
                        to="family.person",
                    ),
                ),
                (
                    "union",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occurrences",
                        to="family.union",
                    ),
                ),
            ],
            options={
                "ordering": ["send_date", "occurrence_date"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("channel", models.CharField(choices=[("email", "Email"), ("sms", "SMS")], max_length=10)),
                ("destination", models.CharField(max_length=255)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField()),
                ("html_body", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("queued", "Queued"), ("sent", "Sent"), ("failed", "Failed")],
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("provider_response", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("tries", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "broadcast",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="notifications.broadcast",
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="notifications.occurrence",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="eventtype",
            constraint=models.UniqueConstraint(
                fields=("family", "code"), name="unique_event_type_code_per_family"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.CheckConstraint(
                condition=models.Q(("person__isnull", False), ("union__isnull", False), _negated=True),
                name="preference_not_both_person_and_union",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "immediate_family_only"), _negated=True),
                    models.Q(("person__isnull", True), ("union__isnull", True)),
                    _connector="OR",
                ),
                name="immediate_family_only_is_whole_type_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                condition=models.Q(("person__isnull", True), ("union__isnull", True)),
                fields=("account", "event_type", "channel"),
                name="unique_whole_type_preference",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                condition=models.Q(("person__isnull", False)),
                fields=("account", "event_type", "channel", "person"),
                name="unique_person_preference",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                condition=models.Q(("union__isnull", False)),
                fields=("account", "event_type", "channel", "union"),
                name="unique_union_preference",
            ),
        ),
        migrations.AddIndex(
            model_name="occurrence",
            index=models.Index(fields=["send_date", "is_sent"], name="notificatio_send_da_d2e3d4_idx"),
        ),
        migrations.AddConstraint(
            model_name="occurrence",
            constraint=models.UniqueConstraint(
                fields=("person", "event_type", "hebrew_year"), name="unique_person_occurrence"
            ),
        ),
        migrations.AddConstraint(
            model_name="occurrence",
            constraint=models.UniqueConstraint(
                fields=("union", "event_type", "hebrew_year"), name="unique_union_occurrence"
            ),
        ),
        migrations.AddConstraint(
            model_name="occurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("person__isnull", False), ("union__isnull", True)),
                    models.Q(("person__isnull", True), ("union__isnull", False)),
                    _connector="OR",
                ),
                name="occurrence_exactly_one_of_person_or_union",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("broadcast__isnull", True), ("occurrence__isnull", False)),
                    models.Q(("broadcast__isnull", False), ("occurrence__isnull", True)),
                    _connector="OR",
                ),
                name="message_exactly_one_of_occurrence_or_broadcast",
            ),
        ),
        migrations.RunPython(seed_global_event_types, unseed_global_event_types),
    ]
