# Generated by Django 6.1.1 on 2026-09-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="broadcast",
            options={"ordering": ["-send_at", "pk"]},
        ),
        migrations.AlterModelOptions(
            name="eventtype",
            options={"ordering": ["name", "pk"]},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-created_at", "pk"]},
        ),
        migrations.AlterModelOptions(
            name="notificationpreference",
            options={"ordering": ["-created_at", "pk"]},
        ),
        migrations.AlterModelOptions(
            name="occurrence",
            options={"ordering": ["send_date", "occurrence_date", "pk"]},
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="shifted_for_shabbat_or_yomtov",
            field=models.BooleanField(default=False, verbose_name="shifted for Shabbat/Yom Tov"),
        ),
    ]
