# Generated by Django 6.1.1 on 2026-09-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_broadcast_options_alter_eventtype_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrence",
            name="send_date",
            field=models.DateField(
                help_text="The date the notification actually goes out (shifted for Shabbos/Yom Tov)"
            ),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="shifted_for_shabbat_or_yomtov",
            field=models.BooleanField(default=False, verbose_name="shifted for Shabbos/Yom Tov"),
        ),
    ]
