# Generated by Django 6.1.1 on 2026-09-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_occurrence_send_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="occurrence",
            name="shifted_for_shabbat_or_yomtov",
        ),
        migrations.AddField(
            model_name="occurrence",
            name="shift_reasons",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
