# Generated by Django 6.1.1 on 2026-09-21 16:28, hand-edited to reorder the
# default_opt_in -> default_state backfill ahead of dropping the old field,
# and to re-seed/update Yahrzeit's own config for the ancestors-aware
# scheduling design (see AGENTS.md's yahrzeit-ancestors notes).

from django.conf import settings
from django.db import migrations, models


def _backfill_default_state(apps, schema_editor):
    EventType = apps.get_model("notifications", "EventType")
    EventType.objects.filter(default_opt_in=True).update(default_state="subscribed")
    EventType.objects.filter(default_opt_in=False).update(default_state="muted")


def _unbackfill_default_state(apps, schema_editor):
    EventType = apps.get_model("notifications", "EventType")
    EventType.objects.filter(default_state="subscribed").update(default_opt_in=True)
    EventType.objects.exclude(default_state="subscribed").update(default_opt_in=False)


def _configure_yahrzeit(apps, schema_editor):
    """Brings the global Yahrzeit EventType in line with the new always_schedule/ancestors_only design.

    update_or_create rather than a plain update() - the row was deleted
    by hand in prod while this feature was being designed (see AGENTS.md),
    so this needs to work whether the global row still exists or not.
    """
    EventType = apps.get_model("notifications", "EventType")
    EventType.objects.update_or_create(
        family=None,
        code="yahrzeit",
        defaults={
            "name": "Yahrzeit",
            "anchor": "death",
            "applies_to_union": False,
            "default_state": "ancestors_only",
            "always_schedule": True,
            "recurs": True,
            "notify_days_before": 0,
        },
    )


def _revert_yahrzeit_config(apps, schema_editor):
    """Reverting this migration just puts Yahrzeit's config back to the pre-migration shape.

    Never deletes the row - that would undo real (or test) data the
    forward migration didn't create, since the row may have already
    existed before this migration ran.
    """
    EventType = apps.get_model("notifications", "EventType")
    EventType.objects.filter(family=None, code="yahrzeit").update(
        default_state="subscribed", always_schedule=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0002_alter_person_options_alter_union_options_and_more"),
        ("notifications", "0004_remove_occurrence_shifted_for_shabbat_or_yomtov_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notificationpreference",
            name="immediate_family_only_is_whole_type_only",
        ),
        migrations.AddField(
            model_name="eventtype",
            name="always_schedule",
            field=models.BooleanField(
                default=False,
                help_text="Whether this event type's occurrences are computed even for an untracked (notifications_enabled=False) subject - e.g. Yahrzeit, so a real ancestor entered only as a lineage stub can still have their yahrzeit surfaced to whoever actually wants it (see AGENTS.md). Only affects whether the Occurrence gets computed at all, not who's notified - that's still resolved per-account, same as any other event type.",
            ),
        ),
        migrations.AddField(
            model_name="eventtype",
            name="default_state",
            field=models.CharField(
                choices=[
                    ("muted", "Muted"),
                    ("subscribed", "Subscribed"),
                    ("immediate_family_only", "Immediate family only"),
                    ("ancestors_only", "Ancestors only"),
                ],
                default="subscribed",
                help_text="What people are set to for this event type unless they say otherwise - subscribed, muted, or scoped to their immediate family/ancestors by default. A family adding a more sensitive custom event type may want it to start muted instead.",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="state",
            field=models.CharField(
                choices=[
                    ("muted", "Muted"),
                    ("subscribed", "Subscribed"),
                    ("immediate_family_only", "Immediate family only"),
                    ("ancestors_only", "Ancestors only"),
                ],
                max_length=25,
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state__in", ["immediate_family_only", "ancestors_only"]), _negated=True),
                    models.Q(("person__isnull", True), ("union__isnull", True)),
                    _connector="OR",
                ),
                name="family_scope_states_are_whole_type_only",
            ),
        ),
        migrations.RunPython(_backfill_default_state, _unbackfill_default_state),
        migrations.RemoveField(
            model_name="eventtype",
            name="default_opt_in",
        ),
        migrations.RunPython(_configure_yahrzeit, _revert_yahrzeit_config),
    ]
