# Generated by Django 6.1.1 on 2026-09-20 22:03

from django.db import migrations, models

CHANNEL_VALUE_RENAMES = {"email": "Email", "sms": "SMS"}


def rename_channel_values(apps, schema_editor):
    """Rewrites existing Message/NotificationPreference rows to ChannelEnum's new friendly values.

    Old rows still hold the pre-rename lowercase values ("email"/"sms")
    - choices= isn't DB-enforced, so they'd otherwise silently stop
    matching every `channel == ChannelEnum.EMAIL`-style comparison in
    app code (notifications.tasks, notifications.audience, ...) once
    the enum's own value changes underneath them.
    """
    Message = apps.get_model("notifications", "Message")
    NotificationPreference = apps.get_model("notifications", "NotificationPreference")
    for model in (Message, NotificationPreference):
        for old_value, new_value in CHANNEL_VALUE_RENAMES.items():
            model.objects.filter(channel=old_value).update(channel=new_value)


def rename_channel_values_reverse(apps, schema_editor):
    Message = apps.get_model("notifications", "Message")
    NotificationPreference = apps.get_model("notifications", "NotificationPreference")
    for model in (Message, NotificationPreference):
        for old_value, new_value in CHANNEL_VALUE_RENAMES.items():
            model.objects.filter(channel=new_value).update(channel=old_value)


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_remove_occurrence_shifted_for_shabbat_or_yomtov_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="channel",
            field=models.CharField(choices=[("Email", "Email"), ("SMS", "SMS")], max_length=10),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="channel",
            field=models.CharField(choices=[("Email", "Email"), ("SMS", "SMS")], max_length=10),
        ),
        migrations.RunPython(rename_channel_values, rename_channel_values_reverse),
    ]
