# Generated by Django 6.1.1 on 2026-09-21 22:29, hand-edited to add the
# ancestors_only -> direct_family_only data rename (see AGENTS.md's
# yahrzeit-extended-family notes) - the preference now covers immediate
# family plus the whole ancestor/descendant line at any depth, both for
# the account and its own current spouse, not just direct ancestors, so
# the old name no longer describes it.

from django.conf import settings
from django.db import migrations, models


def _rename_ancestors_only_to_direct_family_only(apps, schema_editor):
    EventType = apps.get_model("notifications", "EventType")
    NotificationPreference = apps.get_model("notifications", "NotificationPreference")
    EventType.objects.filter(default_state="ancestors_only").update(default_state="direct_family_only")
    NotificationPreference.objects.filter(state="ancestors_only").update(state="direct_family_only")


def _rename_direct_family_only_to_ancestors_only(apps, schema_editor):
    EventType = apps.get_model("notifications", "EventType")
    NotificationPreference = apps.get_model("notifications", "NotificationPreference")
    EventType.objects.filter(default_state="direct_family_only").update(default_state="ancestors_only")
    NotificationPreference.objects.filter(state="direct_family_only").update(state="ancestors_only")


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0002_alter_person_options_alter_union_options_and_more"),
        ("notifications", "0006_default_notify_days_before"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notificationpreference",
            name="family_scope_states_are_whole_type_only",
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="default_state",
            field=models.CharField(
                choices=[
                    ("muted", "Muted"),
                    ("subscribed", "Subscribed"),
                    ("immediate_family_only", "Immediate family only"),
                    ("direct_family_only", "Direct family only"),
                ],
                default="subscribed",
                help_text="What people are set to for this event type unless they say otherwise - subscribed, muted, or scoped to their direct family by default. A family adding a more sensitive custom event type may want it to start muted instead.",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="state",
            field=models.CharField(
                choices=[
                    ("muted", "Muted"),
                    ("subscribed", "Subscribed"),
                    ("immediate_family_only", "Immediate family only"),
                    ("direct_family_only", "Direct family only"),
                ],
                max_length=25,
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state__in", ["immediate_family_only", "direct_family_only"]), _negated=True),
                    models.Q(("person__isnull", True), ("union__isnull", True)),
                    _connector="OR",
                ),
                name="family_scope_states_are_whole_type_only",
            ),
        ),
        migrations.RunPython(
            _rename_ancestors_only_to_direct_family_only, _rename_direct_family_only_to_ancestors_only
        ),
    ]
