# Generated by Django 6.1.1 on 2026-09-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0007_direct_family_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventtype",
            name="anchor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("birth", "Date of birth"),
                    ("death", "Date of death (yahrzeit)"),
                    ("marriage", "Marriage date"),
                    ("engagement", "Engagement date"),
                ],
                help_text="Blank for an event type with no anchor date of its own (e.g. Broadcast, which is sent immediately/on a schedule rather than computed from a Person/Union date field).",
                max_length=10,
            ),
        ),
    ]
