# Generated by Django 6.1.1 on 2026-10-02 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0009_engagement_event_types"),
        ("tenants", "0002_alter_family_options_alter_familymembership_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="message",
            name="message_exactly_one_of_occurrence_or_broadcast",
        ),
        migrations.AddField(
            model_name="message",
            name="direct_family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="tenants.family",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("broadcast__isnull", True),
                        ("direct_family__isnull", True),
                        ("occurrence__isnull", False),
                    ),
                    models.Q(
                        ("broadcast__isnull", False),
                        ("direct_family__isnull", True),
                        ("occurrence__isnull", True),
                    ),
                    models.Q(
                        ("broadcast__isnull", True),
                        ("direct_family__isnull", False),
                        ("occurrence__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="message_exactly_one_of_occurrence_broadcast_or_direct_family",
            ),
        ),
    ]
